version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3000:4000'
    volumes:
      - './server:/app'
  testing:
    build:
      context: ./testing
      dockerfile: Dockerfile
    ports:
      - '4000:3000'  
    volumes:
      - './testing:/app'