version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - './server:/app'
  testing:
    build:
      context: ./testing
      dockerfile: Dockerfile
    ports:
      - '80:3000'  # Змінено порт на 80
    volumes:
      - './testing:/app'